### ISSUE TITLE
How to use Directional Custom Blocks?

### ISSUE THREAD

**Issue by Mikarific** [MMonkeyKiller/CustomBlocks#10]
I've noticed that you have support for Directional Custom Blocks, but I don't quite understand how they are implemented. Can you add how this is done to the Wiki?

**Comment by Momaxguy** [comment]
Me too!

**Comment by MMonkeyKiller** [comment]
Hello! Sorry, i forgot to add that on the wiki. This method is only available for developers using the api (for now), you need to register the block with the api, but the block needs to be created extending `DirectionalCustomBlock` and implementing his methods.
I'm gonna add this info to the wiki as soon as I can

**Comment by Momaxguy** [comment]
Can you explain this a bit more?
