### ISSUE TITLE
Rotatable blocks

### ISSUE THREAD

**Issue by Momaxguy** [MMonkeyKiller/CustomBlocks#11]
How do I Add rotateable blocks? Can you please explain?

**Comment by Momaxguy** [comment]
Also How About interactable

**Comment by Momaxguy** [comment]
I cant Get It to work

**Comment by MMonkeyKiller** [comment]
Hello, I updated the wiki to include the information of how to create a directional block.
https://github.com/MMonkeyKiller/CustomBlocks/wiki/EN_UsingTheAPI
