### ISSUE TITLE
[Bug]: Blocks are not placeable.

### ISSUE THREAD

**Issue by ErythroCraft** [MMonkeyKiller/CustomBlocks#16]
**Describe the bug**
Blocks are not placeable.
Maybe I got a misstake.

**To Reproduce (if is possible)**
1. Edit example model (watch out uploaded zip file)
2. texture loaded

**Expected behavior**
Enable to place the example table.

**Screenshots**

![2022-04-29_14 17 56](https://user-images.githubusercontent.com/76217862/165943584-9e46d7d9-0404-48d7-83f3-525a5c5cb535.png)

**Server Info (please complete the following information):**
- 3482-Spigot-42b6152-e87f2e3 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
- [NBTAPI] Loading NBTAPI v2.9.2
- [CustomBlocks] Loading CustomBlocks v3.0.1-SNAPSHOT

[example_pack.zip](https://github.com/MMonkeyKiller/CustomBlocks/files/8590741/example_pack.zip)

**Comment by fan87** [comment]
You should provide more information about it. For example, Is there any active plugins, if so, what are they? If there are custom plugins, can you upload them, or even provide the source?

I don't think it's a bug, chance of blocks not even placeable is pretty pretty low - All builds should be tested and most features should work, it's very hard to not notice it and still publish the plugin.

Also, the texture doesn't affect either client-side block behavior and server-side block placement. The `Reproduce` section is basically equal to saying nothing.

Few things you could check:
 - Do you have OP? If not, is spawn protection on?
 - Do you have any other plugins installed?
 - If so, do you have any plugin that is probably going to cancel the block placement?
 
Some information you can provide:
 - A clip that shows block placement before and after loading the texture
 - Server log
 - Plugins list
 - Compiled Jar file or source of custom plugins
 - If possible - entire server directory (upload in zip)

**Comment by ErythroCraft** [comment]
**Only installed plugins on the test server are** 

- 3482-Spigot-42b6152-e87f2e3 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
- [NBTAPI] Loading NBTAPI v2.9.2
- [CustomBlocks] Loading CustomBlocks v3.0.1-SNAPSHOT

**I uploaded the test server plugin folder and the example pack**

[plugins.zip](https://github.com/MMonkeyKiller/CustomBlocks/files/8617231/plugins.zip)
[example_pack.zip](https://github.com/MMonkeyKiller/CustomBlocks/files/8617242/example_pack.zip)

**Comment by ErythroCraft** [comment]
https://youtu.be/q8qolGzUddk

**Comment by ErythroCraft** [comment]
[2022-05-04-1.log.gz](https://github.com/MMonkeyKiller/CustomBlocks/files/8617273/2022-05-04-1.log.gz)

**Comment by ErythroCraft** [comment]
Do you find the probleme?

**Comment by ErythroCraft** [comment]
@MMonkeyKiller @fan87 
Do you find the probleme?

**Comment by fan87** [comment]
Please update the title to `[Help] Custom block textures are not being rendered`. I can't help you because I don't make resource packs.

But you can google it by keywords like: `Custom Noteblock Texture Tutorial`, I'll update it later.

Pretty sure it's not a bug, I think there's a problem with your texture pack, I'm still checking it.

**Comment by fan87** [comment]
Update: As I said, I didn't do any single research about Minecraft resource packs, but I found out that you don't have blockstate file in your resource pack, and that is **probably** the cause of it.


In your case, add a json file: `assets/minecraft/blockstates/note_block.json`, and put this in it:
```json
{
    "variants": {
        "instrument=banjo,note=0":[{"model":"customcrafting:item/example"}]
    }
}
```

You also have to change the `banjo` and `0` (at `note=0`) to the instrument name and note you've configured

**Comment by ErythroCraft** [comment]
Thanks. I tested the plugin and it will working by edding your example fix.
