### ISSUE TITLE
Cannot break blocks

### ISSUE THREAD

**Issue by DragonsAscent** [MMonkeyKiller/CustomBlocks#3]
I currently cannot break blocks after placing them. I'm running off the latest release off the github and I'm using Paper 1.16.5. Everything seems to be running normally besides the blocks not being able to be broken.

Paper Version: `git-Paper-638`
MC Version: `1.16.5`

Custom Blocks: `1.6-Snapshot`
NBTAPI: `2.7.1`

Blocks also seem to flash whenever something updates above or below them.

**Comment by MMonkeyKiller** [comment]
Hello! The flashing is a bug what i trying to patch soon.
Is any error in the console when you try to break a block?

**Comment by DragonsAscent** [comment]
Unfortunately there's no error when I try to break blocks. I did try to patch a quick issue with this (https://github.com/MMonkeyKiller/CustomBlocks/blob/7b5ddc3c646b82ebd7033a89f899a3e9e6bf7207/src/main/java/me/monkeykiller/customblocks/listeners/Events.java#L201) being on a new line instead of on the same line. The blocks just stay together. If I use the essentials /break command, the block successfully breaks and drops itself. It's something to do with players trying to break it.

(Wasn't able to patch it due to the commodore bug as I'm unable to fix it myself apparently)

**Comment by MMonkeyKiller** [comment]
I'm on that 👍!

**Comment by MMonkeyKiller** [comment]
> Unfortunately there's no error when I try to break blocks. I did try to patch a quick issue with this (
> 
> https://github.com/MMonkeyKiller/CustomBlocks/blob/7b5ddc3c646b82ebd7033a89f899a3e9e6bf7207/src/main/java/me/monkeykiller/customblocks/listeners/Events.java#L201
> 
> ) being on a new line instead of on the same line. The blocks just stay together. If I use the essentials /break command, the block successfully breaks and drops itself. It's something to do with players trying to break it.
> (Wasn't able to patch it due to the commodore bug as I'm unable to fix it myself apparently)

Can you rec a clip when you try to break the block? Is any WorldEdit region defined? Have you tested if this still happen in localhost?

**Comment by DragonsAscent** [comment]
When I break a block it just instantly comes back, there are no worldguard regions defined since I actually just regenerated my world and reset worldguard (making a 2.0 of my server). I've gone through it pretty extensively. Why is it working on your end?

If it works on your end I can get back to you when I'm at my computer but it's going to take me a while since I'm headed to work and won't be back for about 15 hours.

**Comment by MMonkeyKiller** [comment]
> When I break a block it just instantly comes back, there are no worldguard regions defined since I actually just regenerated my world and reset worldguard (making a 2.0 of my server). I've gone through it pretty extensively. Why is it working on your end?
> 
> If it works on your end I can get back to you when I'm at my computer but it's going to take me a while since I'm headed to work and won't be back for about 15 hours.

Oh ok, don't worry. 
I added a temporal debug feature, you need to enable `debug_mode` in config.yml. Try to break a block again, then check in the console if is any message about `[CustomBlocks][DEBUG] `, it not has any important debug info, is going to check where the bug is

**Comment by DragonsAscent** [comment]
Unfortunately, even with the latest update, this is not fixed. This video should help.

There is absolutely NO debug in console even with the setting set to `true`

https://user-images.githubusercontent.com/24839115/117559135-c68e0300-b050-11eb-8af2-0fcd3ea65cdf.mp4

**Comment by MMonkeyKiller** [comment]
> Unfortunately, even with the latest update, this is not fixed. This video should help.
> 
> There is absolutely NO debug in console even with the setting set to `true`
> 
> I can break other blocks, so can my other players, its just custom blocks.

Hmmm... That's weird... Can we talk on discord? i need you to test possible fixes in your local server and fix it in the final plugin. I can't send you an friend request. I'm MonkeyKiller#9506
