### ISSUE TITLE
Page Problem

### ISSUE THREAD

**Issue by uPorter** [MMonkeyKiller/CustomBlocks#4]
If we add more items on a single page, our blocks page interface does not open.

**Comment by uPorter** [comment]
I would like to pass by sending your discord username

**Comment by MMonkeyKiller** [comment]
Sorry, i was making some work. I'm on that!

**Comment by uPorter** [comment]
you are doing excellent work I have a few things I would like to talk to you about a server project Porter#2333 I would be glad if you contact me

**Comment by MMonkeyKiller** [comment]
Solved in [1.9-SNAPSHOT](https://github.com/MMonkeyKiller/CustomBlocks/releases/tag/1.9-SNAPSHOT) update. Closing issue!
