### ISSUE TITLE
Suggestion: Support tripwire based blocks 

### ISSUE THREAD

**Issue by Conrad-Thomas** [MMonkeyKiller/CustomBlocks#5]
This plugin is amazing and is was we've been looking for, but something that would be an amazing addition would be tripwire based blocks. This is perfect for plants and other blocks you allow people to walk through.

Below is an example of the file blockstates/tripwire.json

Contact Me on discord: ConradHD#4655

```
{
    "multipart": [
        {
            "apply": {
                "model": "custom/example1"
            },
            "when": {
                "attached": "false",
                "disarmed": "false",
                "east": "false",
                "north": "false",
                "powered": "false",
                "south": "false",
                "west": "false"
            }
        },
        {
            "apply": {
                "model": "custom/example2"
            },
            "when": {
                "attached": "false",
                "disarmed": "false",
                "east": "false",
                "north": "true",
                "powered": "false",
                "south": "false",
                "west": "false"
            }
        }
    ]
}
```

**Comment by MMonkeyKiller** [comment]
Hello! It's a great suggestion, i was thinking on that. 
I think the best way to implement this option is by an addon for the plugin

Anyway, I will keep thinking about adding this option to the plugin, if it is not a big problem to add it to the code and make it readable.
