### ISSUE TITLE
Can't set the custom block name.

### ISSUE THREAD

**Issue by verwischt** [MMonkeyKiller/CustomBlocks#8]
**Describe the bug**
We create the config for the new block, as the wiki says, but the name of the item shows a strange string. Differently to the example block, that shows the name correctly.

**To Reproduce (if is possible)**
1. run the command /customblocks add customblocks:test1 1004 BANJO 01 false

**Expected behavior**
The name Test1 in the item.

**Screenshots**
![Screenshot](https://i.imgur.com/3sru7dN.png)

**Server Info (please complete the following information):**
 - Paper
 - 3.0.1-SNAPSHOT
 - 1.16.5

**Comment by MMonkeyKiller** [comment]
Hello! That's the translation key for the custom block. Check the `assets/minecraft/lang/` folder on the example resource pack

**Comment by verwischt** [comment]
Ah! Ok. My friend is a dumb! Thanks for the response. hahahaha
Anyway, i was thinking... Is your plan add a "disable blockstate" for tripwire too?
