### ISSUE TITLE
This Is Not a Problem

### ISSUE THREAD

**Issue by Momaxguy** [MMonkeyKiller/CustomBlocks#9]
I am not the best at JavaScript and I am wondering how to turn this into a plugin when I am done. How do I turn the .zip to a .jar?

**Comment by Momaxguy** [comment]
![unknown](https://user-images.githubusercontent.com/95580747/153784067-dee184b8-8f4a-4db0-897a-17c474163f03.png)
Maybe Someone could just send me the working jar file?

**Comment by MMonkeyKiller** [comment]
Hello! You can download the latest version of the plugin in the `Releases` tab: https://github.com/MMonkeyKiller/CustomBlocks/releases

**Comment by Momaxguy** [comment]
Hi thank u for helping me! You are only person who had what I was looking for. This was a huge help!! 🙂
